spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath*:db/schema-ddl.sql
      data-locations: classpath:db/trims-data.sql

mybatis:
  type-aliases-package: com.h2o.h2oServer.domain
  mapper-locations: static/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

