name: Java Gradle Test

on:
  pull_request:
    branches: 'ci-test-main'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run :
        working-directory : ./backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution : 'temurin'
        java-version: 11

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Tests
      run: ./gradlew test

    - name: Check Test Results
      run: |
        if [ ${{ job.status }} == "failure" ]; then
          echo "Tests failed. PR cannot be merged."
          exit 1
        fi



