name: Java Gradle Test

on:
  pull_request:
    branches: 'ci-test-main'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run :
        working-directory : ./backend
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
      
    - name: Build with Gradle
      run: ./gradlew build

    - name : print
      run : ls

    - name: Run Tests
      run: ./gradlew test

    - name: Check Test Results
      run: |
        if [ ${{ job.status }} == "failure" ]; then
          echo "Tests failed. PR cannot be merged."
          exit 1
        fi
